USE [master]
GO

/****** Object:  Database [GardnerSql]    Script Date: 4/3/2021 8:36:54 PM ******/
CREATE DATABASE [GardnerSql]
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [GardnerSql].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [GardnerSql] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [GardnerSql] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [GardnerSql] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [GardnerSql] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [GardnerSql] SET ARITHABORT OFF 
GO

ALTER DATABASE [GardnerSql] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [GardnerSql] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [GardnerSql] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [GardnerSql] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [GardnerSql] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [GardnerSql] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [GardnerSql] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [GardnerSql] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [GardnerSql] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [GardnerSql] SET  DISABLE_BROKER 
GO

ALTER DATABASE [GardnerSql] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [GardnerSql] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [GardnerSql] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [GardnerSql] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [GardnerSql] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [GardnerSql] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [GardnerSql] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [GardnerSql] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [GardnerSql] SET  MULTI_USER 
GO

ALTER DATABASE [GardnerSql] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [GardnerSql] SET DB_CHAINING OFF 
GO

ALTER DATABASE [GardnerSql] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [GardnerSql] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [GardnerSql] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [GardnerSql] SET QUERY_STORE = OFF
GO

USE [GardnerSql]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [GardnerSql] SET  READ_WRITE 
GO

